### ISSUE TITLE
I'd like to present my solutions and discuss with the course!

### ISSUE THREAD

**Issue by stellafelicitas** [BMCV/mobi-fs5-python#6]
### Repository

mobi-fs5-python

### Access rights

- [X] I hereby confirm that the supervisors can access my GitHub repository.

### Git commit and push

- [X] I hereby confirm that I have committed and pushed to my GitHub repository.

### Lab session

Introduction (Cheat Sheet)

**Comment by kostrykin** [comment]
Thanks!
