### ISSUE TITLE
I'd like to present my solutions and discuss with the course!

### ISSUE THREAD

**Issue by ennoschaefer** [BMCV/mobi-fs5-python#8]
### Repository

mobi-fs5-python

### Access rights

- [X] I hereby confirm that the supervisors can access my GitHub repository.

### Git commit and push

- [X] I hereby confirm that I have committed and pushed to my GitHub repository.

### Lab session

Lab Session 1

### Additional context for the comments

Task 1

**Comment by kostrykin** [comment]
Thanks!
