### ISSUE TITLE
Things aren't working and I'm stuck!

### ISSUE THREAD

**Issue by PhilippScheulen** [BMCV/mobi-fs5-python#9]
### Repository

philipp-does-fun-hacker-stuff

### Access rights

- [X] I hereby confirm that the supervisors can access my GitHub repository.

### Git commit and push

- [X] I hereby confirm that I have committed and pushed to my GitHub repository.

### Task

Lab Session 2

### Describe the problem (if possible)

Wrong thresholds:
> Image: 28, Dice: 0.75, T=35
Image: 29, Dice: 0.65, T=41
Image: 33, Dice: 0.60, T=60
Image: 44, Dice: 0.59, T=64
**Image: 46, Dice: 0.37, T=58**
Image: 49, Dice: 0.80, T=46

Should be:
> Image: 28, Dice: 0.75, T=35
Image: 29, Dice: 0.65, T=41
Image: 33, Dice: 0.43, T=71
Image: 44, Dice: 0.58, T=67
**Image: 46, Dice: 0.08, T=75**
Image: 49, Dice: 0.80, T=46

**Comment by kostrykin** [comment]
The error was in the computation of your histogram:
```python
    h = np.zeros(255)
    for x in range(255):
        h[x]= np.sum(img8 == x)
```
This should be:
```python
    h = np.zeros(256)
    for x in range(256):
        h[x]= np.sum(img8 == x)
```
In your implementation, the frequencies of intensity 255 were not computed, and thus not considered by your Otsu implementation.
